### ISSUE TITLE
make paper-fab default background be --accent-color

### ISSUE THREAD

**Issue by kasperpeulen** [PolymerElements/paper-fab#12]
What about using the `--accent-color` in `paper-styles/default-theme.html` to be the default background color for paper-fabs ?

Like material pallete also does: http://www.materialpalette.com/indigo/pink

currently, the default theme styles it like this:
![image](https://cloud.githubusercontent.com/assets/1035299/7940531/ddc76edc-0951-11e5-9181-103b63912b29.png)

it look like this if you style it with the accent-color:
![image](https://cloud.githubusercontent.com/assets/1035299/7940522/ce8ff3c6-0951-11e5-8c2a-e6e3c5350d4e.png)

So I used:
```
  <style is="custom-style">
    :root {
      --paper-fab-background: var(--accent-color);
    }
  </style>
```

I think styling it like this makes more sense, also at this moment, the default accent color isn't used by any paper-elements, which is maybe a bit odd.

**Comment by notwaldorf** [comment]
Ah, this is my bad. I thought the pink was too pink in all the other instances of this button, and gave it a more sedated default :)

I'll restore it to it's bright, shiny `--accent-color` 

(/cc @cdata)
