### ISSUE TITLE
Ripple on the paper-fab is not exactly round when in Chrome's device mode and viewing on mobile devices

### ISSUE THREAD

**Issue by motss** [PolymerElements/paper-fab#16]
Is there something wrong with the <paper-ripple> on basically all the round element like <paper-fab>?
The ripple is not exactly round when in Chrome's device mode and viewing it on mobile devices, the square ripple will appear as well. No such issue occur when self-creating a custom element with <paper-ripple>.

![screenshot from 2015-06-28 23-24-42_modified](https://cloud.githubusercontent.com/assets/10607759/8907780/ca5f8b5c-34aa-11e5-9933-c32005d072eb.png)

**Comment by ronnyroeller** [comment]
+1

**Comment by kromacode** [comment]
+1

**Comment by notwaldorf** [comment]
@motss can you re-add your screenshot, please? the link seems to be broken

**Comment by motss** [comment]
@notwaldorf fixed broken image!

**Comment by notwaldorf** [comment]
Oh, I believe the square is because `cursor:pointer` on mobile adds a default webkit-tap colour. Fixing!
