### ISSUE TITLE
paper-fab-menu

### ISSUE THREAD

**Issue by biancashouse** [PolymerElements/paper-fab#25]
http://cwdoh.com/paper-fab-menu/components/paper-fab-menu/demo.html

So paper-fab-menu is not a Polymer element ?
It is created on top of Polymer, right ?
Is there a paper Polymer element that does this popup menu functionality ?

**Comment by GabiAxel** [comment]
I created an element for adding morphing and speed dial to a fab: https://github.com/GabiAxel/paper-fab-transitions/

**Comment by ebidel** [comment]
This issue was moved to PolymerElements/paper-elements#44
