### ISSUE TITLE
Bug in README.md; path inclusion should be to paper-fab.html

### ISSUE THREAD

**Issue by iislucas** [PolymerElements/paper-fab#27]
I think it should be: 
```
<link href="path/to/paper-fab/paper-fab.html" rel="import">

<paper-fab icon="add"></paper-fab>
<paper-fab mini icon="favorite"></paper-fab>
<paper-fab src="star.png"></paper-fab>
```

(current README says iron-icons.html)

**Comment by notwaldorf** [comment]
It should be both. You need to include `paper-fab.html` to be able to use `<paper-fab>`, it's true, but the example was meant to illustrate that if you want to use an `icon` in the button, you need to also include `iron-icons`
