### ISSUE TITLE
Feature request- shadow attribute for hover and non hover

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-fab#33]
It seems there are variations on what the shadow should be for `floating-action-button`. 

For instance, 

[Google's action button documenation](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions) shows a tight shadow.

But, in it's real life use [it shows a much heavier shadow](https://design.google.com/articles/expressing-brand-in-material/)

I suppose since there is no definite rule on what the shadow should be, a attribute to adjust the shadow before hover and a additional shadow attribute for non hover would be best.

**Comment by notwaldorf** [comment]
This is already available as a mixin. If you import `paper-styles/shadow.html`, then you can style your buttons like so:

```css
<style is="custom-style">
paper-fab.flat {
  @apply(--shadow-none);
}
paper-fab.deep {
  @apply(--shadow-elevation-16dp);
}
</style>
```
