### ISSUE TITLE
v1.0.5 breaks user-styled transitions

### ISSUE THREAD

**Issue by shawncplus** [PolymerElements/paper-fab#34]
See repro with instructions here https://jsbin.com/vixocunafe/1/edit?html,output

**Comment by notwaldorf** [comment]
You need to update all the dependencies, not just `paper-fab` by itself
(since the 1.0.5 change depends on other PRs in paper-behaviours, for
example). If you do a `bower install`, everything should work correctly as
before.

**Comment by notwaldorf** [comment]
Yup, I can repro this. Will take a look. Sorry about the inconvenience in the meantime :cry:
