### ISSUE TITLE
paper-ripple

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/paper-fab#46]
I see paper-ripple.html is imported, but I don't see where it is used.

https://github.com/PolymerElements/paper-fab/blob/master/paper-fab.html#L16

In the 0.5 version, I was able to disable the ripple by :

```
      #backbutton::shadow paper-ripple {
        display: none;
      }
```

but I don't see how to do this with the new version. Any pointers?

**Comment by notwaldorf** [comment]
You can just add the `noink` attribute to the `paper-fab`: http://jsbin.com/navoje/edit?html,output
