### ISSUE TITLE
Embedded paper-tooltip support

### ISSUE THREAD

**Issue by Nejat** [PolymerElements/paper-fab#50]
[paper-tooltip](https://github.com/PolymerElements/paper-tooltip) has a great feature which let's it automatically target it's `parent` or `:host` if it's distributed with the `<content>` tag.

Is there a reason `paper-fab` and more elements do not support this feature? 

Does it have to do with performance or is it something that is in the pipeline?

I was able to successfully modify a local version of `paper-fab` with the following addition ...

```javascript
    .
    .
    .
    
          :host(.keyboard-focus) {
            background: var(--paper-fab-keyboard-focus-background, --paper-pink-900);
          }
        </style>
    
        <iron-icon id="icon" src="[[src]]" icon="[[icon]]"></iron-icon>
        <content select="paper-tooltip"></content>  // <=== this line was added
      </template>
    </dom-module>
    
    .
    .
    .
```

*meanwhile, i'm using my local version until inheritance from custom components are re-introduced*

**Comment by keanulee** [comment]
Hi @Nejat,

You can use `<paper-tooltip for="elemID">` to bind the tooltip to the button. Example: http://jsbin.com/todujuhaya/edit?html,output

**Comment by notwaldorf** [comment]
Here's more details on the reasoning not to do this: https://github.com/PolymerElements/paper-icon-button/pull/32#issuecomment-173856075

**Comment by Nejat** [comment]
Hi @keanulee, thank you I know about the "for" attribute for associating a tooltip with it's target. 

my original question was concerning why don't more components take advance of the tooltip's ability to automatically associate with it's direct parent?

Which one is more performant? 

1) assigning an id to a target element, associating a tooltip with that id which looks up said associated element
or 2) allowing tooltip to be embeddable and let it automatically associate with it's immediate parent, without any need for id's. 

I honestly don't know which one is more performant and memory efficient, but i prefer the latter because it is more declarative-ish

Hi @notwaldorf, thanks for the link, but I wouldn't suggest that implementation either for the same reason stated in that link. my suggestion better resembles this `<paper-fab><paper-tooltip></paper-tooltip></paper-fab>`
