### ISSUE TITLE
Non-standard code: Javascript code is outside the </dom-module> tag instead of inside like other elements

### ISSUE THREAD

**Issue by cherukumilli** [PolymerElements/paper-fab#52]
paper-fab's code is not following the same standards as other elements. paper-fab's javascript code is outside the <dom-module> </dom-module>. All other elements have javascript code inside the <dom-module> </dom-module> tags

### Current paper-fab code:
```
...
<dom-module>
   ...
</dom-module>
<script>
   ...
</script>
```

### Expected:
```
...
<dom-module>
   ...
   <script>
      ...
   </script>
</dom-module>
```

**Comment by abdonrd** [comment]
I created a PR: https://github.com/PolymerElements/paper-fab/pull/53. :blush:
