### ISSUE TITLE
keyboard-focus class is on by default in IE 11

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-fab#55]
![image](https://cloud.githubusercontent.com/assets/971651/12332966/787040de-babf-11e5-8a0d-a94d74807f1a.png)

**Comment by addyosmani** [comment]
Can you confirm if you're also seeing this in Microsoft Edge?

**Comment by govis** [comment]
No, Edge is fine. Thanks
![image](https://cloud.githubusercontent.com/assets/971651/12334351/9d541b16-bac7-11e5-80db-1720487d6db1.png)

**Comment by keanulee** [comment]
This is the same issue as PolymerElements/paper-button#64, which is fixed in PolymerElements/paper-behaviors#41.

tl;dr IE does not support the second argument to `element.classList.toggle()`.

**Comment by keanulee** [comment]
The latest release for paper-behaviors (v1.0.11) includes this fix
