### ISSUE TITLE
srcElement switches randomly between iron-icon and paper-fab element

### ISSUE THREAD

**Issue by Typel** [PolymerElements/paper-fab#57]
I added an on-tap event to a simple paper-fab element, like so:

`<paper-fab id="paperfab" icon="favorite" title="heart" on-tap="_doSomething"></paper-fab>`

Then from my _doSomething function, 

`console.log(e.srcElement.id);`

Tapping this paper-fab several times in a row and then examining the log reveals that the srcElement changes randomly between the paper-fab and the iron-icon contained therein (might depend on where the button was tapped?). It would be nice if the srcElement remained reliably consistent.

**Comment by keanulee** [comment]
Hi @Typel,

You can get a normalized event target by using Polymer's DOM API.

```
Polymer.dom(event).localTarget === <paper-fab>
```

For more details, see https://www.polymer-project.org/1.0/docs/devguide/events.html#retargeting.

Example: http://jsbin.com/dejafanipo/edit?html,output
