### ISSUE TITLE
24dp default margin to match Material spec?

### ISSUE THREAD

**Issue by cpboyd** [PolymerElements/paper-fab#58]
It's not difficult to add via CSS (as I've done below), but should there be a default margin equivalent to 24dp since paper elements are supposed to satisfy the Material Design guidelines?

"The floating action button should be placed 16dp minimum from the edge on mobile and 24dp minimum on tablet/desktop."

```
.content paper-fab {
    position: fixed;
    z-index: 10;
    bottom: 0;
    right: 0;
    margin: 24px;
}
```

**Comment by keanulee** [comment]
Adding that margin styling to the element would be too over-reaching - you can imagine cases where the FAB is inside another container that has sufficient margin, meaning it doesn't need to be specified here. Also, the spec says the minimum margin is different on different devices, which means you would need media queries as well.

Overall, we leave conformance to the spec as a decision to the end developer.
