### ISSUE TITLE
FAB element should import iron-icons.html inspite of iron-icon.html

### ISSUE THREAD

**Issue by swastikpareek** [PolymerElements/paper-fab#64]
Since **paper-fab** needs **iron-icons.html**. As it doesn't loads <svg> in the DOM. I was looking at the polycast on polymer youtube channel and I was trying to add paper-fab element but it was not loading svg icons inside the round button. 

 When I dived inside the bower repository I found out that this element needs **iron-icons** element as dependency.

 But it was not their in the documentations of paper-fab, so I was thinking to add this in the library only so that a user don't need to import **iron-icons** elements separately and only importing paper-fab will do. 

_**Reasons for changes**-_
1. **paper-fab** needs iron-icons by default - User should not explicitly import **iron-icons** if it is importing **paper-fab** .
2. If we import **iron-icons** , it will automatically import **iron-icon** 
3. Bower dependency is already there in _bower.json_ file for **iron-icons**

Also I have removed **iron-icon** dependency from _brower.json_ file of **paper-icons** because it is already there in _bower.json_ of **iron-icons** folder.
 

Link for the PR - 
https://github.com/PolymerElements/paper-fab/pull/63

**Comment by keanulee** [comment]
@swastikpareek iron-icons is not included because not everyone needs all the icons (e.g. a user can use https://github.com/PolymerElements/iron-iconset-svg to define only the icons they need).
