### ISSUE TITLE
Paper Fab component delays rendering on IOS 9.3.2

### ISSUE THREAD

**Issue by sweatstudio** [PolymerElements/paper-fab#73]
Using Paper-Fab component on IOS 9.3.2

Displays properly however page has problem rendering.  Most of the time, it just freezes.  

When Paper-Fab tags are removed, the page successfully renders. 

### Browsers Affected

- [ ] Safari 9

**Comment by keanulee** [comment]
@sweatstudio Can you reproduce in a JSBin? The demo page seems to load fine in iOS https://elements.polymer-project.org/bower_components/paper-fab/demo/index.html

**Comment by sweatstudio** [comment]
@keanulee appears that IOS10 resolved this issue.  I was using i-frames and had to tweak my CSS webkit settings.  Thanks.
